import type { SidebarNavGroupDef } from './types'

/** Vertical-agnostic admin sidebar groups (every tenant sees these when entitled). */
export const coreSidebarGroups: SidebarNavGroupDef[] = [
  {
    id: 'overview',
    title: 'Overview',
    icon: 'LayoutDashboard',
    order: 10,
    items: [
      {
        id: 'dashboard',
        name: 'Dashboard',
        href: '/',
        icon: 'LayoutDashboard',
        permissions: ['view_dashboard'],
        badge: null,
      },
      {
        id: 'analytics',
        name: 'Analytics',
        href: '/analytics',
        icon: 'BarChart2',
        permissions: ['view_analytics'],
        badge: null,
      },
      {
        id: 'catalog_performance',
        name: 'Catalog performance',
        href: '/analytics/catalog',
        icon: 'BarChart2',
        permissions: ['view_analytics'],
        badge: null,
      },
      {
        id: 'growth_funnels',
        name: 'Growth funnels',
        href: '/analytics/funnels',
        icon: 'Target',
        permissions: ['view_analytics'],
        badge: null,
      },
    ],
  },
  {
    id: 'crm',
    title: 'CRM',
    icon: 'Briefcase',
    order: 20,
    items: [
      { id: 'crm_overview', name: 'CRM overview', href: '/crm', icon: 'Briefcase', permissions: ['view_crm'], module: 'crm', badge: null },
      { id: 'crm_leads', name: 'Leads', href: '/crm/leads', icon: 'UserSearch', permissions: ['view_crm'], module: 'crm', badge: null },
      { id: 'crm_contacts', name: 'Contacts', href: '/crm/contacts', icon: 'Users', permissions: ['view_crm'], module: 'crm', badge: null },
      { id: 'crm_companies', name: 'B2B accounts', href: '/crm/companies', icon: 'Building2', permissions: ['view_crm'], module: 'crm', badge: null },
      { id: 'crm_deals', name: 'Deals', href: '/crm/deals', icon: 'Handshake', permissions: ['view_crm'], module: 'crm', badge: null },
      { id: 'crm_activities', name: 'Activities', href: '/crm/activities', icon: 'ListTodo', permissions: ['view_crm'], module: 'crm', badge: null },
      { id: 'crm_settings', name: 'CRM settings', href: '/crm/settings', icon: 'SlidersHorizontal', permissions: ['view_crm'], module: 'crm', badge: null },
    ],
  },
  {
    id: 'money',
    title: 'Money',
    icon: 'CreditCard',
    order: 40,
    items: [
      { id: 'payments', name: 'Payments', href: '/payments', icon: 'CreditCard', permissions: ['view_payments', 'create_payments', 'refund_payments'], badge: null },
      { id: 'invoices', name: 'Invoices', href: '/invoices', icon: 'Receipt', permissions: ['view_payments', 'create_payments', 'refund_payments'], badge: null },
      { id: 'invoice_branding', name: 'Invoice appearance', href: '/invoices/branding', icon: 'Palette', permissions: ['view_payments', 'create_payments', 'refund_payments'], badge: null },
      { id: 'payouts', name: 'Earnings & Payouts', href: '/payouts', icon: 'Landmark', permissions: ['view_payments', 'create_payments', 'refund_payments'], badge: null },
      { id: 'finance', name: 'Finance', href: '/finance/overview', icon: 'TrendingUp', permissions: ['view_finance'], module: 'finance', badge: null },
      {
        id: 'founder_finance',
        name: 'Founder Finance',
        href: '/finance/founder/dashboard',
        icon: 'TrendingUp',
        permissions: ['view_finance'],
        module: 'finance',
        platformOnly: true,
        badge: null,
      },
      { id: 'subscriptions', name: 'Subscriptions', href: '/subscriptions', icon: 'Repeat', permissions: ['view_subscriptions'], badge: null },
      {
        id: 'company_documents',
        name: 'Documents & signatures',
        href: '/company-documents',
        icon: 'FileSignature',
        permissions: ['view_company_documents'],
        badge: null,
      },
    ],
  },
  {
    id: 'team',
    title: 'Team & collaboration',
    icon: 'Users',
    order: 45,
    items: [
      { id: 'boards', name: 'Boards', href: '/boards', icon: 'Presentation', permissions: ['view_boards'], badge: null },
      { id: 'team_work', name: 'Team work', href: '/team-work', icon: 'KanbanSquare', permissions: ['view_team_tasks', 'manage_team_tasks'], module: 'team_work', badge: null },
      { id: 'team_calendar', name: 'Team calendar', href: '/team-work/calendar', icon: 'CalendarDays', permissions: ['view_team_tasks', 'manage_team_tasks'], module: 'team_work', badge: null },
      { id: 'chat', name: 'Chat', href: '/chat', icon: 'MessageCircle', permissions: ['view_messages'], badge: null },
    ],
  },
  {
    id: 'commerce',
    title: 'Commerce',
    icon: 'ShoppingBag',
    order: 55,
    items: [
      {
        id: 'ecommerce',
        name: 'Store overview',
        href: '/ecommerce',
        icon: 'ShoppingBag',
        module: 'ecommerce',
        permissions: [
          'view_products',
          'create_products',
          'view_categories',
          'view_orders',
          'manage_coupons',
          'manage_system_settings',
          'view_settings',
        ],
        badge: null,
      },
      { id: 'products', name: 'Products', href: '/products', icon: 'Package', permissions: ['view_products'], module: 'ecommerce', badge: null },
      {
        id: 'inventory',
        name: 'Inventory',
        href: '/inventory',
        icon: 'Package2',
        permissions: ['view_products', 'edit_products', 'manage_product_inventory'],
        module: 'ecommerce',
        badge: null,
      },
      { id: 'orders', name: 'Orders', href: '/orders', icon: 'ShoppingCart', permissions: ['view_orders'], module: 'ecommerce', badge: null },
      {
        id: 'bazaar',
        name: 'Offers & listing chats',
        href: '/bazaar',
        icon: 'Handshake',
        module: 'bazaar',
        permissions: [
          'view_products',
          'create_products',
          'view_categories',
          'view_orders',
          'manage_coupons',
          'manage_system_settings',
          'view_settings',
        ],
        badge: null,
      },
      {
        id: 'bazaar_listing_review',
        name: 'Listing review',
        href: '/bazaar/listing-review',
        icon: 'ListChecks',
        module: 'bazaar',
        permissions: [
          'view_products',
          'create_products',
          'view_categories',
          'view_orders',
          'manage_coupons',
          'manage_system_settings',
          'view_settings',
        ],
        badge: null,
      },
      {
        id: 'bazaar_module_settings',
        name: 'Module & AI settings',
        href: '/bazaar/module-settings',
        icon: 'Sparkles',
        module: 'bazaar',
        permissions: [
          'view_products',
          'create_products',
          'view_categories',
          'view_orders',
          'manage_coupons',
          'manage_system_settings',
          'view_settings',
        ],
        badge: null,
      },
    ],
  },
  {
    id: 'content_marketing',
    title: 'Content & Marketing',
    icon: 'Globe',
    order: 60,
    items: [
      {
        id: 'cms_site_structure',
        name: 'Site structure',
        icon: 'LayoutGrid',
        hasSubmenu: true,
        module: 'cms',
        permissions: ['view_cms', 'manage_cms'],
        badge: null,
        subItems: [
          { id: 'cms_overview', name: 'CMS overview', href: '/cms', icon: 'Globe', permissions: ['view_cms'], module: 'cms' },
          { id: 'cms_homepage', name: 'Homepage', href: '/cms/homepage', icon: 'Home', permissions: ['manage_cms'], module: 'cms' },
          { id: 'cms_site_appearance', name: 'Site appearance', href: '/cms/site-appearance', icon: 'Palette', permissions: ['manage_cms'], module: 'cms' },
          { id: 'storefront_studio', name: 'Storefront Studio', href: '/settings/storefront', icon: 'Sparkles', permissions: ['manage_cms', 'view_settings'] },
          { id: 'cms_pages', name: 'Pages', href: '/cms/pages', icon: 'FileText', permissions: ['manage_cms'], module: 'cms' },
          { id: 'cms_menus', name: 'Menus', href: '/cms/menus', icon: 'Menu', permissions: ['manage_cms'], module: 'cms' },
          { id: 'cms_media', name: 'Media library', href: '/cms/media', icon: 'Image', permissions: ['manage_cms'], module: 'cms' },
        ],
      },
      {
        id: 'surfaces_promos',
        name: 'Surfaces & promotions',
        icon: 'Sparkles',
        hasSubmenu: true,
        permissions: ['view_cms', 'manage_cms', 'manage_marketing'],
        badge: null,
        subItems: [
          { id: 'sliders', name: 'Sliders & banners', href: '/sliders', icon: 'Images', permissions: ['manage_cms'], module: 'cms' },
          { id: 'coupons', name: 'Coupons & promo codes', href: '/coupons', icon: 'TicketPercent', permissions: ['manage_marketing'], module: 'marketing_workspace' },
          { id: 'cart_tiers', name: 'Cart spend tiers', href: '/marketing/cart-tiers', icon: 'Sparkles', permissions: ['manage_marketing'], module: 'marketing_workspace' },
          { id: 'referrals', name: 'Referrals', href: '/referrals', icon: 'Share2', permissions: ['manage_marketing'], module: 'marketing_workspace' },
        ],
      },
      {
        id: 'editorial',
        name: 'Editorial & social proof',
        icon: 'Newspaper',
        hasSubmenu: true,
        permissions: ['view_cms', 'manage_cms'],
        module: 'cms',
        badge: null,
        subItems: [
          { id: 'blogs', name: 'Blog posts', href: '/cms/blogs', icon: 'BookOpen', permissions: ['manage_cms'], module: 'cms' },
          { id: 'blog_categories', name: 'Blog categories', href: '/cms/blog-categories', icon: 'Tag', permissions: ['manage_cms'], module: 'cms' },
          { id: 'newsletter', name: 'Newsletter', href: '/cms/newsletter', icon: 'Megaphone', permissions: ['manage_cms'], module: 'cms' },
          { id: 'email_templates', name: 'Email templates', href: '/cms/email-templates', icon: 'Mail', permissions: ['manage_system_settings'], module: 'cms' },
          { id: 'social_links', name: 'Social links', href: '/cms/social-links', icon: 'Link2', permissions: ['manage_cms'], module: 'cms' },
          { id: 'testimonials', name: 'Testimonials', href: '/cms/testimonials', icon: 'Star', permissions: ['manage_cms'], module: 'cms' },
          { id: 'reviews', name: 'Reviews', href: '/cms/reviews', icon: 'Star', permissions: ['manage_cms'], module: 'cms' },
          { id: 'faqs', name: 'FAQs', href: '/cms/faqs', icon: 'HelpCircle', permissions: ['manage_cms'], module: 'cms' },
        ],
      },
      {
        id: 'seo_core',
        name: 'SEO',
        icon: 'Search',
        hasSubmenu: true,
        permissions: ['manage_cms', 'manage_system_settings'],
        module: 'cms',
        badge: null,
        subItems: [
          { id: 'seo_management', name: 'SEO management', href: '/cms/seo', icon: 'Search', permissions: ['manage_cms'], module: 'cms' },
          { id: 'seo_recent_jobs', name: 'Recent Jobs (SEO)', href: '/cms/recent-jobs-seo', icon: 'Briefcase', permissions: ['manage_system_settings'], module: 'cms' },
        ],
      },
      {
        id: 'marketing_workspace',
        name: 'Marketing workspace',
        icon: 'Megaphone',
        hasSubmenu: true,
        permissions: ['manage_cms', 'manage_marketing'],
        module: 'marketing_workspace',
        badge: null,
        subItems: [
          { id: 'mkt_overview', name: 'Overview', href: '/marketing', icon: 'LayoutGrid', permissions: ['manage_coupons'], module: 'marketing_workspace' },
          { id: 'mkt_campaigns', name: 'Campaigns', href: '/marketing/campaigns', icon: 'Target', permissions: ['manage_coupons'], module: 'marketing_workspace' },
          { id: 'mkt_calendar', name: 'Content calendar', href: '/marketing/calendar', icon: 'Calendar', permissions: ['manage_coupons'], module: 'marketing_workspace' },
          { id: 'mkt_social', name: 'Social posts', href: '/marketing/social', icon: 'Share2', permissions: ['manage_coupons'], module: 'marketing_workspace' },
          { id: 'mkt_planning', name: 'Planning & ideas', href: '/marketing/planning', icon: 'Lightbulb', permissions: ['manage_coupons'], module: 'marketing_workspace' },
          { id: 'mkt_tasks', name: 'Tasks', href: '/marketing/tasks', icon: 'ListTodo', permissions: ['manage_coupons'], module: 'marketing_workspace' },
          { id: 'mkt_lab', name: 'R&D & brainstorm', href: '/marketing/lab', icon: 'FlaskConical', permissions: ['manage_coupons'], module: 'marketing_workspace' },
        ],
      },
    ],
  },
  {
    id: 'people',
    title: 'People & messaging',
    icon: 'Users',
    order: 70,
    items: [
      { id: 'customers', name: 'Customers', href: '/users/customers', icon: 'Users', permissions: ['view_users', 'manage_users'], badge: null },
      { id: 'team_members', name: 'Team members', href: '/users/members', icon: 'BadgeCheck', permissions: ['view_users', 'manage_users'], badge: null },
      { id: 'notifications', name: 'Notifications', href: '/notifications', icon: 'Bell', permissions: ['view_notifications', 'manage_notifications'], badge: null },
    ],
  },
  {
    id: 'knowledge',
    title: 'Knowledge kit',
    icon: 'BookOpen',
    order: 80,
    items: [
      { id: 'kk_overview', name: 'Guides overview', href: '/knowledge-kit', icon: 'BookOpen', permissions: ['view_dashboard'], badge: null },
    ],
  },
  {
    id: 'system',
    title: 'System',
    icon: 'Settings',
    order: 100,
    items: [
      { id: 'reports', name: 'Reports', href: '/reports', icon: 'LineChart', permissions: ['view_reports'], badge: null },
      { id: 'system_status', name: 'System Status', href: '/system-status', icon: 'Cloud', permissions: ['view_system_status'], badge: null },
      { id: 'refund_requests', name: 'Refund requests', href: '/support/refund-requests', icon: 'Wallet', permissions: ['refund_payments'], badge: null },
      { id: 'support_tickets', name: 'Support tickets', href: '/support/tickets', icon: 'TicketPercent', permissions: ['view_dashboard'], badge: null },
      { id: 'settings', name: 'Settings', href: '/settings', icon: 'Settings', permissions: ['manage_settings'], badge: null },
      { id: 'access', name: 'Roles & access', href: '/settings/access', icon: 'Shield', permissions: ['view_settings', 'manage_system_settings', 'manage_user_roles'], badge: null },
      { id: 'help', name: 'Help & Support', href: '/support', icon: 'LifeBuoy', permissions: ['view_dashboard'], badge: null },
      { id: 'saas_platform', name: 'Launch readiness', href: '/settings/saas', icon: 'Rocket', permissions: ['manage_settings'], platformOnly: true, badge: null },
      { id: 'organizations', name: 'Organizations', href: '/settings/tenants', icon: 'Building2', permissions: ['manage_system_settings'], platformOnly: true, badge: null },
    ],
  },
]
