import type { SidebarNavGroupDef, VerticalPackDefinition } from '../core/types'
import { homeServicesBookingEngagement } from './engagement'
import { homeServicesDashboardLayout } from './dashboardWidgets'
import { homeServicesBillingPlans } from './billingPlans'
import {
  homeServicesCatalogKinds,
  homeServicesCompliance,
  homeServicesIntegrations,
  homeServicesReports,
  homeServicesTaxStrategy,
  homeServicesWorkforceRoles,
} from './packExtras'

/** Home services / trades / on-site marketplace — vertical-specific sidebar. */
export const homeServicesSidebarGroups: SidebarNavGroupDef[] = [
  {
    id: 'hs_operations',
    title: 'Operations',
    icon: 'Calendar',
    order: 30,
    items: [
      { id: 'bookings', name: 'Bookings', href: '/bookings', icon: 'Calendar', permissions: ['view_bookings', 'manage_bookings'], badge: null },
      { id: 'amc', name: 'AMC contracts', href: '/amc/overview', icon: 'ShieldCheck', permissions: ['view_amc'], badge: null },
      { id: 'rate_cards', name: 'Rate cards', href: '/rate-cards/overview', icon: 'ListOrdered', permissions: ['view_rate_cards'], badge: null },
      { id: 'fees_cities', name: 'Fees & cities', href: '/operations/commercial/terms', icon: 'CircleDollarSign', permissions: ['view_operating_terms'], badge: null },
      { id: 'provider_assets', name: 'Professional assets', href: '/operations/provider-assets', icon: 'Boxes', permissions: ['view_provider_assets'], badge: null },
      { id: 'professional_conduct', name: 'Conduct & incentives', href: '/operations/professional-conduct', icon: 'Gavel', permissions: ['view_professional_conduct'], badge: null },
      { id: 'home_services_pos', name: 'POS — Home services', href: '/operations/pos', icon: 'ScanLine', permissions: ['create_bookings', 'manage_bookings'], badge: null },
      { id: 'industry_ops', name: 'Industry operations', href: '/operations', icon: 'Gauge', permissions: ['view_dashboard'], badge: null },
      { id: 'dispute_cases', name: 'Dispute cases', href: '/operations/dispute-cases', icon: 'ShieldAlert', permissions: ['view_bookings', 'manage_bookings', 'edit_bookings'], badge: null },
      { id: 'service_requests', name: 'Service requests', href: '/requests', icon: 'ClipboardList', permissions: ['view_services', 'manage_services'], badge: null },
      { id: 'quotes', name: 'Quotes', href: '/quotes', icon: 'DollarSign', permissions: ['view_quotes'], badge: null },
    ],
  },
  {
    id: 'hs_catalog',
    title: 'Catalog & network',
    icon: 'Package',
    order: 50,
    items: [
      { id: 'product_categories', name: 'Product categories', href: '/categories/products', icon: 'Package2', permissions: ['view_categories', 'manage_categories'], module: 'ecommerce', badge: null },
      { id: 'service_categories', name: 'Service categories', href: '/categories/services', icon: 'Wrench', permissions: ['view_categories', 'manage_categories'], badge: null },
      { id: 'platform_services', name: 'Platform services', href: '/platform-services', icon: 'Home', permissions: ['view_services', 'manage_services'], badge: null },
      {
        id: 'marketplace',
        name: 'Marketplace',
        href: '/marketplace',
        icon: 'Store',
        permissions: [
          'view_services',
          'view_categories',
          'view_bookings',
          'view_providers',
          'view_payments',
          'manage_coupons',
          'manage_system_settings',
        ],
        badge: null,
      },
      { id: 'professionals', name: 'Professionals', href: '/professionals', icon: 'User', permissions: ['view_providers', 'edit_providers', 'approve_providers'], badge: null },
      { id: 'workforce_dashboard', name: 'Workforce dashboard', href: '/professionals/operations', icon: 'KanbanSquare', permissions: ['view_providers', 'edit_providers', 'approve_providers'], badge: null },
      { id: 'provider_applications', name: 'Provider Applications', href: '/provider-applications', icon: 'IdCard', permissions: ['view_providers', 'edit_providers', 'approve_providers'], badge: null },
      {
        id: 'bazaar_pro_verify',
        name: 'Pro-Verify queue',
        href: '/bazaar/pro-verify',
        icon: 'BadgeCheck',
        module: 'bazaar',
        permissions: [
          'view_products',
          'create_products',
          'view_categories',
          'view_orders',
          'manage_coupons',
          'manage_system_settings',
          'view_settings',
        ],
        badge: null,
      },
    ],
  },
  {
    id: 'hs_industry_growth',
    title: 'Industry growth',
    icon: 'Layers',
    order: 62,
    items: [
      {
        id: 'industry_landing',
        name: 'Industry — Landing & SEO',
        href: '/cms/category-marketing',
        icon: 'Megaphone',
        permissions: ['manage_system_settings'],
        module: 'cms',
        badge: null,
      },
      {
        id: 'industry_service_areas',
        name: 'Industry — Service areas',
        href: '/cms/category-marketing?tab=service-areas',
        icon: 'MapPin',
        permissions: ['manage_system_settings'],
        module: 'cms',
        badge: null,
      },
      {
        id: 'industry_rate_card',
        name: 'Industry — Rate card',
        href: '/cms/category-marketing?tab=rate-card',
        icon: 'Receipt',
        permissions: ['manage_system_settings'],
        module: 'cms',
        badge: null,
      },
      {
        id: 'industry_cross_linking',
        name: 'Industry — Cross-linking',
        href: '/cms/category-marketing?tab=cross-linking',
        icon: 'Link2',
        permissions: ['manage_system_settings'],
        module: 'cms',
        badge: null,
      },
      {
        id: 'service_combos',
        name: 'Service bundles',
        href: '/marketing/service-combos',
        icon: 'Layers',
        permissions: ['manage_marketing'],
        module: 'marketing_workspace',
        badge: null,
      },
    ],
  },
]

export const homeServicesPack: VerticalPackDefinition = {
  key: 'home_services',
  label: 'Home Services',
  description:
    'On-site services dispatched to a customer address: plumbing, electrical, cleaning, appliance repair, and related trades.',
  version: '1.0.0',
  defaultModules: [
    'cms',
    'crm',
    'finance',
    'marketing_workspace',
    'team_work',
    'bazaar',
    'ecommerce',
  ],
  sidebarGroups: homeServicesSidebarGroups,
  engagementTypes: [homeServicesBookingEngagement],
  dashboardLayout: homeServicesDashboardLayout,
  billingPlans: homeServicesBillingPlans,
  catalogKinds: homeServicesCatalogKinds,
  workforceRoles: homeServicesWorkforceRoles,
  taxStrategy: homeServicesTaxStrategy,
  compliance: homeServicesCompliance,
  integrations: homeServicesIntegrations,
  reports: homeServicesReports,
  marketingSlug: 'for-home-services',
}
